version: "3.5"

services:
  scaffold:
    image: cincarnato/dracul-scaffold
    container_name: scaffold
    volumes:
      - ./media:/apps/api/dist/media
      - ./logs:/apps/api/dist/logs
      - ./.env:/apps/api/dist/.env
    ports:
      - "80:5000"
    network_mode: host
