version: "3.5"

services:
  draculscaffold:
    image: cincarnato/dracul-scaffold
    container_name: draculscaffold
    volumes:
      - ./media:/app/media
      - ./logs:/app/logs
      - ./.env:/app/.env
    ports:
      - "80:5000"
